#!/bin/sh

set -e

WORKDIR=$(mktemp -d)
trap "rm -rf $WORKDIR" 0 INT QUIT ABRT PIPE TERM
cd $WORKDIR

gsasl --version
gsasl --help

gsasl --version|(! grep '()')
echo "PASS: gsasl libgsasl version"

man -P cat gsasl
echo "PASS: man"
